### PR TITLE
enhancement: option to inject a custom openAPI generator

### PR DESCRIPTION
**Pull request by fschade**
## Description

Allow users to inject a custom OpenAPI generator via the server options.
This enhancement provides flexibility for users to define their own OpenAPI schemas based on their specific needs.

## Example
Please check the added docs and examples.

## Changes

- Added a new option in the `Server` struct  to hold the custom OpenAPI generator.
- Updated the `RegisterOpenAPIOperation` function to use the custom OpenAPI generator when generating schemas for request and response bodies.

It has been tested and all existing tests pass.

### CODE REVIEW

**Comment by EwenQuim** [comment]
As we will be dropping `getkin-openapi` for OpenAPI 3.1 support, we won't support this issue.

But
- using exported fields
- readonly fields
- descriptions
will be supported with the OpenAPI3.1 support! Stay tuned, this should be coming soon

**Comment by EwenQuim** [comment]
As we will be dropping `getkin-openapi` for OpenAPI 3.1 support, we won't support this issue.

But
- using exported fields
- readonly fields
- descriptions
will be supported with the OpenAPI3.1 support! Stay tuned, this should be coming soon

---

Don't hesitate to raise an issue before working hard on a PR!

**Comment by fschade** [comment]
No problem, thanks for the info. Is there any help needed for the 3.1 transition?

**Comment by dylanhitt** [comment]
@EwenQuim can we close this?

**Comment by EwenQuim** [comment]
@fschade we currently don't need help for the 3.1 transition, but thank you very much for the proposal !

**Pull request closed without merging**
