### PR TITLE
sort go imports

### PR DESCRIPTION
**Pull request by ccoVeille**
- **chore: sort go imports**
- **ci: add gci to golangci-lint**
- **chore: update (and sometimes fix) the examples in documentation**
- **chore: format Markdown block with [mdsf](https://github.com/hougesen/mdsf)**

The idea is to use the following pattern                                                                                                                                                   

```go                                                                                                                                                                                               
import (                                                                                                                                                                                   
        // std lib imports                                                                                                                                                                     
                                                                                                                                                                                               
        // third party imports                                                                                                                                                                 
                                                                                                                                                                                               
        // package imports from fuego                                                                                                                                                          
)                                                                                                                                                                                          
```

More information about this in the following discussion

#184

### CODE REVIEW

**Review by asahasrabuddhe — APPROVED** [review]
LGTM

**Comment by ccoVeille** [comment]
I added 2 commits, please review them

I used [mdsf](https://github.com/hougesen/mdsf), which provide a good result

**Review by EwenQuim — COMMENTED** [review]
Thanks!

Do you know if there is a way to make IDEs do it automatically, or if golangci-lint will fix them automatically?

I don't want to add more steps for contributors: if it adds friction I will not merge the linter check, just the modifications you proposed.

**Comment by ccoVeille** [comment]
Please look at what I said here

https://github.com/go-fuego/fuego/discussions/184#discussioncomment-10511397

gopls can be configured with formatting.local

**Comment by ccoVeille** [comment]
Also if the CI fails, gci will provide the exact command line to run to fix the issues

Also, golangci-lint can be run with --fix to format the files.

So, it's only a matter of documentation

**Comment by EwenQuim** [comment]
Perfect!

Thanks

**Review by EwenQuim — APPROVED** [review]

**Pull request merged**
