### PR TITLE
Hide route from OpenAPI spec, variadic options way

### PR DESCRIPTION
**Pull request by EwenQuim**
@dylanhitt for reference.

I'm merging this as it is a really small PR

### CODE REVIEW

**Review by dylanhitt — APPROVED** [review]
👍

**Comment by EwenQuim** [comment]
I didn't think you'd be so quick to approve haha

**Comment by dylanhitt** [comment]
I should probably be asleep 😅

**Comment by EwenQuim** [comment]
Haha yes, good night!

I just woke up, I live in Europe.

**Pull request merged**
