### PR TITLE
Enhance query parameters to support a list of parameters

### PR DESCRIPTION
**Pull request by dhanielsales**
Related issue: https://github.com/go-fuego/fuego/issues/167

### CODE REVIEW

**Review by EwenQuim — APPROVED** [review]

**Comment by dylanhitt** [comment]
Instead of QueryParamArr. Why don’t we just just fix the concept of QueryParam to return an array?

**Comment by EwenQuim** [comment]
> Instead of QueryParamArr. Why don’t we just just fix the concept of QueryParam to return an array?

Because 90% of the time only one param is used, so it's more convenient. That's why the std lib uses [0] also by default

image

**Comment by dhanielsales** [comment]
Exactly. The standard type `url.Values` have a Get method to return the first value on the slice.

**Comment by dylanhitt** [comment]
Ah, excellent points. This is great!

**Review by dylanhitt — APPROVED** [review]

**Pull request merged**
